# Generated by Django 4.1.4 on 2023-01-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_vendor_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='country',
        ),
    ]
