# Generated by Django 4.1.4 on 2023-02-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_userrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_in_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
